### ISSUE TITLE
Performance issues on Docker

### ISSUE THREAD

**Issue by FireMasterK** [spikecodes/libreddit#315]
## Describe the bug
Libreddit on Docker, seems to take a **REALLY** long time to respond (~20-30s).

## To reproduce
```
mkdir libreddit && cd libreddit
edit docker-compose.yml # automatically uses your favorite editor
```
paste the following:
```
services:
  web:
    image: spikecodes/libreddit:latest
    restart: unless-stopped
    container_name: "libreddit"
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s
```
save the file.
run:
```
docker-compose up -d
time curl -s -S -o /dev/null 127.0.0.1:8080
```

## Expected behavior
Libreddit responds in requests in under a second or two

## Additional context
It's affecting my instance currently, and also affects my local environment, which has a 5800H.
