### ISSUE TITLE
Environment variables do not work in Docker

### ISSUE THREAD

**Issue by Stolz** [spikecodes/libreddit#437]
## Describe the bug
The official Docker image does not apply settings set via environment variables

## To reproduce

Create Docker compose file with some environment variables
```
version: '3'
services:
  libReddit:
    environment:
      AUTOPLAY_VIDEOS: 'on'        # on, off
      COMMENT_SORT: 'top'          # hot, new, top, rising, controversial
      FRONT_PAGE: 'popular'        # default, popular, all
      HIDE_HLS_NOTIFICATION: 'on'  # on, off
      LAYOUT: 'card'               # card, clean, compact
      POST_SORT: 'confidence'      # confidence, top, new, controversial, old
      SHOW_NSFW: 'on'              # on, off
      THEME: 'nord'                # system, light, dark, black, dracula, nord, laserwave, violet, gold, rosebox
      USE_HLS: 'on'                # on, off
      WIDE: 'on'                   # on, off
    image: spikecodes/libreddit:latest
    ports:
      - "8080:8080"
```
Start the Docker container
```
$ docker-compose up -d
Creating libreddit ... done
Attaching to libreddit
libreddit    | Starting Libreddit...
libreddit    | Running Libreddit v0.21.7 on 0.0.0.0:8080!
```
Verify environment variables are indeed set
```
$ docker exec libreddit env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=libreddit
AUTOPLAY_VIDEOS=on
COMMENT_SORT=top
FRONT_PAGE=popular
HIDE_HLS_NOTIFICATION=on
LAYOUT=card
POST_SORT=confidence
SHOW_NSFW=on
THEME=nord
USE_HLS=on
WIDE=on
HOME=/nonexistent
```

Visit <http://localhost:8080>

## Expected behavior

Custom settings should be applied.
