### ISSUE TITLE
💡 Feature request: Allow custom adding custom CSS 

### ISSUE THREAD

**Issue by helium18** [spikecodes/libreddit#486]
## Is your feature request related to a problem? Please describe.

The contrast of all the contents in general is low. It's hard to distinguish the cards from the background

## Describe the feature you would like to be implemented

Allow a custom css option from settings which allows the user to set the colors for different sections of the page if they wish to. 

## Describe alternatives you've considered

[Whoogle-search](https://github.com/benbusby/whoogle-search) for example has this feature wherein you can add custom css. It's not exactly raw css with selectors, but its easy enough for people to understand. 

## Additional context / screenshot

![image](https://user-images.githubusercontent.com/86223025/163660202-0ee9c588-8790-42ed-a264-fa4e706ded44.png)

An example configuration would be 

```css
:root {
    --card: red;
    --bg: blue;
    --text: green;
    --search: grey;
    /* ... etc */
}
```
