### ISSUE TITLE
[Enhancement] Kubernetes deployment files

### ISSUE THREAD

**Issue by 11Tuvork28** [spikecodes/libreddit#494]
So I have been wanting to host libreddit for a while now but since I couldn't find files for hosting on kubernetes and I was lazy I haven't gotten around to writing them. But now I finally had enough motivation so here you go(I orianted my along the docker-compose file):

<details>

 <summary>deployment.yaml:</summary>

 ```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libreddit-deployment
  labels:
    app: libreddit-libreddit
    release: Libreddit-alpha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: libreddit-libreddit
      release: Libreddit-alpha
  template:
    metadata:
      labels:
        app: libreddit-libreddit
        release: Libreddit-alpha
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: libreddit-container
        image: "spikecodes/libreddit:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            port: 8080
            path: /settings
        livenessProbe:
          httpGet:
            port: 8080
            path: /settings
          initialDelaySeconds: 15
          periodSeconds: 300
      restartPolicy: Always
```
</details>

<details>

 <summary>service.yaml:</summary>

```
apiVersion: v1
kind: Service
metadata:
  name: libreddit-service
  labels:
    app: libreddit-libreddit
    release: Libreddit-alpha
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: libreddit-libreddit
    release: Libreddit-alpha
```
</details>

The ingress part come down to what ingress controller you're using so it doesn't make sense to put mine in here, tho keep in my when writing them that the service name is ```libreddit-service``` on port ```8080```
If you have improvements by all means improve/correct my files I'm  not a 'pro', this is running [at](https://reddit.beta.xamh.de/)

Anyways thats it I thought it would be helpful to share them, if wanted I can submit a PR
